config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "friends", to: "pages#friends"
  get "calendar", to: "pages#calendar"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def calendar
  end

  def friends
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # #before_action :authenticate_user!, except: [ :home ]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_form.html.erb
<div class="d-flex justify-content-center align-items-center vh-100">
<div class="w-40 p-4 border rounded shadow" style="width: 40%">
<div class="container" style="width: 30%">
    <form class="row g-3" >
     
    <div class="form-control" style="border: 0px, width: 100%">
  
  <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name">
</div>

    <select class="form-select" aria-label="Default select example">
    <option selected>Interest Nº 1</option>
    <option value="1">One</option>
    <option value="2">Two</option>
    <option value="3">Three</option>
    </select>
    <select class="form-select" aria-label="Default select example">
    <option selected>Interest Nº 2</option>
    <option value="1">One</option>
    <option value="2">Two</option>
    <option value="3">Three</option>
    </select>

    <div class="form-check">
    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
    <label class="form-check-label" for="flexRadioDefault1">
        Male
    </label>
    </div>
    <div class="form-check">
    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
    <label class="form-check-label" for="flexRadioDefault2">
        Female
    </label>
    </div>
    <label for="customRange2" class="form-label">Price range</label>
    <input type="range" class="form-range" min="0" max="5" id="customRange2">
    <label for="customRange2" class="form-label">Age</label>
    <input type="range" class="form-range" min="0" max="5" id="customRange2">
    <button type="button" class="btn btn-outline-primary">Randomize</button>
    
    </form>
    </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="pages#home">Dadan</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Friends</a>
        </li>
        <li> <%= link_to "Calendar", calendar_path, class:"nav-link" %></li>
        <li> <%= link_to "Friends", friends_path, class:"nav-link" %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
            <li> <%= link_to "Edit Profile", edit_user_registration_path, class:"dropdown-item"%></li>
          </ul>
      
          </ul>
    </div>
  </div>
</nav>
          <% elsif %>
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <li> <%= link_to "Dadan", root_path, class:"navbar-brand" %> </li>
                <li> <%= link_to "Sign Up", new_user_registration_path, class:"navbar-brand"%> </li>
                  <li> <%= link_to "Log In", new_user_session_path, class:"navbar-brand" %> </li>
                  </nav>
                </div>
    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Gift Randomizer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>

  </body>
</html>

app/views/pages/calendar.html.erb
<p>ciaoo!</p>

app/views/pages/home.html.erb
<%= render "layouts/form"%> 